import "../styles/index.css";
import type { Metadata } from "next";
import { fonts } from "../styles/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fonts}>
      <body className="theme-dark theme-current">{children}</body>
    </html>
  );
}
